import typing

@typing.overload
def str2bool(value: str, raise_exc: typing.Literal[False] = False) -> typing.Optional[bool]: ...

@typing.overload
def str2bool(value: str, raise_exc: typing.Literal[True]) -> bool: ...

def str2bool(value: str, raise_exc: bool = False) -> typing.Optional[bool]: ...
def str2bool_exc(value: str) -> bool: ...
